service:
  name: nestjs-serverless

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  environment:
    CONFIG_ENV: Config ENV working!

package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*'
            headers: '*'
